CREATE DATABASE agro;

USE agro;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(25) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE postagem (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(100),
    descricao VARCHAR(300),
    imagem BLOB
);

CREATE TABLE login(
    id INT AUTP_INCREMENT PRIMARY KEY,
    nome
)